Repository defenseunicorns/pepr, pull requests merged in 2024-09, with the labels that each got.

#916 feat: add alias prefixing to pino logs
  docs/030_user-guide/030_actions/050_using-alias-child-logger.md
  package-lock.json
  src/lib/capability.test.ts
  src/lib/capability.ts
  src/lib/mutate-processor.ts
  src/lib/schedule.ts
  src/lib/types.ts
Labels: Lula

#1161 refactor: filterNoMatchReason and shouldSkipRequest
  src/fixtures/data/create-pod.json
  src/fixtures/data/delete-pod.json
  src/lib/adjudicators.test.ts
  src/lib/adjudicators.ts
  src/lib/filter.test.ts
  src/lib/filter.ts
  src/lib/helpers.test.ts
  src/lib/helpers.ts
Labels: tech-debt

#1176 feat: redact store values from logs
  docs/030_user-guide/120_customization.md
  src/lib/controller/store.test.ts
  src/lib/controller/store.ts
  src/lib/storage.ts
Labels: uds
