Repository defenseunicorns/pepr, pull requests merged in 2024-12, with the labels that each got.

#1486 refactor: resolve eslint warnings (max-statements, complexity)
  src/lib/controller/index.ts
  src/lib/controller/index.util.test.ts
  src/lib/controller/index.util.ts
Labels: tech-debt

#1497 refactor: resolve eslint warnings (max-statements, complexity) - `src/lib/assets/index.ts`
  src/lib/assets/index.ts
Labels: tech-debt

#1402 chore(ts): add typing to adjudicators used in validation and mutation processing
  src/lib/capability.ts
  src/lib/filter/adjudicators.test.ts
  src/lib/filter/adjudicators.ts
  src/lib/filter/adjudicators/bindingAdjudicators.test.ts
  src/lib/filter/adjudicators/bindingKubernetesObjectAdjudicators.test.ts
  src/lib/filter/adjudicators/defaultTestObjects.ts
  src/lib/filter/adjudicators/requestAdjudicators.test.ts
  src/lib/filter/filter.test.ts
  src/lib/filter/shouldSkipRequest.test.ts
  src/lib/helpers.test.ts
  src/lib/helpers.ts
  src/lib/types.ts
Labels: tech-debt, Testing, large

#1520 test: validate `pepr build` generates a `helm install`-able chart
  .github/workflows/deploy-helm.yml
Labels: Testing

#1529 refactor: resolve eslint warnings (max-depth, complexity) - src/lib/validate-processor.ts
  src/lib/validate-processor.test.ts
  src/lib/validate-processor.ts
Labels: tech-debt

#1543 refactor: resolve eslint warnings (max-depth, complexity) - src/lib/mutate-processor.ts
  src/lib/mutate-processor.test.ts
  src/lib/mutate-processor.ts
Labels: tech-debt

#1577 refactor: resolve eslint warnings (max-depth, complexity) - src/cli/deploy.ts
  src/cli/deploy.ts
Labels: tech-debt

#1571 chore: warn devs when their feature branches may be too large
  .husky/pre-commit
  .husky/pre-push
  docs/120_contribute/README.md
Labels: SPIKE

#1585 refactor: resolve eslint warnings (complexity) - src/lib/filter/filterNoMatchReason.ts
  src/lib/filter/filter.test.ts
  src/lib/filter/filter.ts
  src/lib/filter/filterNoMatchReason.ts
  src/lib/filter/shouldSkipRequest.test.ts
  src/lib/helpers.test.ts
  src/lib/processors/watch-processor.ts
Labels: tech-debt
